version: '2'

services:
  db:
    image: mariadb
    container_name: e-vento_db
    ports:
    - 1234:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - e-vento-db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 2222:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  e-vento-db:
